title: "Controlled Hallucination"
author: "Arnab Chatterjee"
description: "The Wheel weaves us all into the Pattern. You have no freedom about it, but by the Light you can still face it on your feet" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
#The Wheel weaves us all into the Pattern. You have ~~less~~ no freedom about it, but by the Light you can still face it on your feet.
#Some doxography but mostly commentary on philosophical works
#The Wheel weaves us all into the Pattern as it wills. You have less freedom about it than most, but by the Light, you can still face it on your feet.
# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "arnabchat21@gmail.com"
#twitter_username: "twitteruser"
#github_username: "perrin-ay"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
